In [1]:
!pip install -U scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 27.6 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
from sklearn import datasets,model_selection


In [4]:
import pandas as pd
from sklearn import datasets

# Import Iris dataset
iris = datasets.load_iris()

# Create a DataFrame from the Iris dataset
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target


# Print the type of iris object
print(type(iris))


<class 'sklearn.utils._bunch.Bunch'>


In [5]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [6]:
iris_df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [7]:
iris_df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [8]:
iris_df.drop_duplicates()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[149 rows x 5 columns]

In [9]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [10]:
# selected_rows = iris_df.iloc[:-1,]
# selected_rows

# selected_rows = iris_df.iloc[:,0:-1]
# selected_rows

In [11]:
##select all rows and all columns except the last one.

X = iris_df.iloc[:,  :-1]



##select all rows, but only the last column.

y = iris_df.iloc[:, -1]


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=49)

# Convert the data to NumPy arrays if needed
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)
X_test = np.asarray(X_test)
y_test = np.asarray(y_test)


In [13]:
x=X_train.min(axis=0)
print(x)

[4.3 2.  1.  0.1]


In [14]:
X_train[0]

array([5.7, 3.8, 1.7, 0.3])

In [15]:
import numpy as np

# Calculate minimum and maximum values for each feature in the training set
X_train_min = X_train.min(axis=0)
X_train_max = X_train.max(axis=0)

# Calculate minimum and maximum values for each feature in the test set
X_test_min = X_test.min(axis=0)
X_test_max = X_test.max(axis=0)

# Initialize lists to store normalized values
X_train_normalized = []
X_test_normalized = []

# Normalize the training set
for i in range(len(X_train)):
    x = (X_train[i] - X_train_min) / (X_train_max - X_train_min)
    X_train_normalized.append(x)

# Normalize the test set using the same normalization parameters as the training set
for i in range(len(X_test)):
    x = (X_test[i] - X_test_min) / (X_test_max - X_test_min)
    X_test_normalized.append(x)

# Convert the lists to NumPy arrays
X_train_normalized = np.asarray(X_train_normalized)
X_test_normalized = np.asarray(X_test_normalized)

# Print the normalized training and test sets
print("Normalized training set:")
print(X_train_normalized)
print("\nNormalized test set:")
print(X_test_normalized)


Normalized training set:
[[0.38888889 0.75       0.11864407 0.08333333]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.52777778 0.08333333 0.59322034 0.58333333]
 [0.25       0.875      0.08474576 0.        ]
 [0.36111111 0.20833333 0.49152542 0.41666667]
 [0.72222222 0.45833333 0.69491525 0.91666667]
 [0.19444444 0.5        0.03389831 0.04166667]
 [0.66666667 0.20833333 0.81355932 0.70833333]
 [0.91666667 0.41666667 0.94915254 0.83333333]
 [0.47222222 0.08333333 0.6779661  0.58333333]
 [0.22222222 0.70833333 0.08474576 0.125     ]
 [0.08333333 0.66666667 0.         0.04166667]
 [0.94444444 0.75       0.96610169 0.875     ]
 [0.19444444 0.125      0.38983051 0.375     ]
 [0.5        0.41666667 0.66101695 0.70833333]
 [0.33333333 0.16666667 0.47457627 0.41666667]
 [0.55555556 0.20833333 0.6779661  0.75      ]
 [0.13888889 0.58333333 0.15254237 0.04166667]
 [0.80555556 0.41666667 0.81355932 0.625     ]
 [0.66666667 0.41666667 0.71186441 0.91666667]
 [0.58333333 0.5        0.72881356 

In [16]:
def distance_ecu(X_train_normalized, x_test_point):
    """
    Input:
        - X_train_normalized : normalized training data
        - x_test_point : test point to calculate distances from

    Output:
        - distances : The distances between the test point and each point in the training data.
    """
    distances = []

    # Loop over the rows of X_train_normalized
    for i in range(len(X_train_normalized)):

        # Get the point by point
        current_train_point = X_train_normalized[i]
        current_distance = 0

        # Loop over the columns of the row
        for j in range(len(x_test_point)):
            current_distance += (current_train_point[j] - x_test_point[j])**2

        current_distance = current_distance**0.5

        # Append the distances
        distances.append(current_distance)

    # Store distances in a dataframe
    distances = pd.DataFrame(data=distances, columns=['distance'])
    return distances

In [17]:
def nearest_neighbors(distances, k):
    """
    Input:
        - distances : The distances between the test point and each point in the training data.
        - k : The number of neighbors to consider.

    Output:
        - df_nearest : The nearest K neighbors between the test point and the training data.
    """
    # Sort distances using the sort_values function
    df_nearest = distances.sort_values(by='distance')

    # Take only the first K neighbors
    df_nearest = df_nearest.iloc[:k]

    return df_nearest

In [18]:
def nearest_neighbors(distances, k, y_train):
    """
    Input:
    - distances : The distances between the test point and each point in the training data.
    - k : The number of neighbors to consider.
    - y_train: The labels of the training dataset.

    Output:
        - df_nearest : The nearest K neighbors between the test point and the training data.
    """
    # Sort distances using the sort_values function
    df_nearest = distances.sort_values(by='distance')

    # Take only the first K neighbors
    df_nearest = df_nearest.iloc[:k]

    # Add corresponding labels to df_nearest
    df_nearest['target'] = y_train[df_nearest.index]

    return df_nearest


In [19]:
from collections import Counter

def voting(df_nearest):
    """
    Input:
    - df_nearest: DataFrame containing the nearest K neighbors between the full training dataset and the test point.

    Output:
        - y_pred: The prediction based on majority voting.
    """
    # Use the Counter object to get the labels with K nearest neighbors
    counter_vote = Counter(df_nearest['target'])

    # Perform majority voting
    y_pred = counter_vote.most_common(1)[0][0]

    return y_pred


In [20]:
def KNN_from_scratch(X_train_normalized, X_test_normalized, y_train, K):
    """
    Input:
    - X_train_normalized: The normalized full training dataset
    - X_test_normalized: The normalized full test dataset
    - y_train: The labels of the training dataset
    - K: The number of neighbors

    Output:
    - y_pred: The prediction for the whole test set based on Majority Voting
    """
    y_pred = []  # Initialize the list to store predictions

    # Loop over all the test set and perform the three steps
    for x_test_point in X_test_normalized:
        # Step 1: Calculate distances
        distances = distance_ecu(X_train_normalized, x_test_point)

        # Step 2: Get nearest neighbors
        df_nearest_point = nearest_neighbors(distances, K, y_train)  # Pass y_train as an argument

        # Step 3: Perform Majority Voting
        y_pred_point = voting(df_nearest_point)

        y_pred.append(y_pred_point)  # Append the prediction for the current test point to the list of predictions

    return y_pred

In [21]:
#test at k = 3
K = 3
y_pred_scratch =KNN_from_scratch(X_train_normalized,X_test_normalized,y_train,K)

print(y_pred_scratch)

[1, 2, 1, 2, 2, 0, 2, 2, 2, 2, 0, 1, 0, 1, 1, 1, 1, 2, 2, 0, 0, 1, 0, 2, 0, 1, 1, 2, 0, 2]


In [22]:


def test_knn(X_train_normalized, X_test_normalized, y_train, K):
    """
    Test KNN classifier using scikit-learn implementation.

    Inputs:
    - X_train_normalized: The normalized full training dataset
    - X_test_normalized: The normalized full test dataset
    - y_train: The labels of the training dataset
    - K: The number of neighbors

    Returns:
    - y_pred_sklearn: The predicted labels for the test set using scikit-learn's KNN
    """

    # Instantiate the KNN classifier
    knn = KNeighborsClassifier(n_neighbors=K)

    # Fit the classifier to the training data
    knn.fit(X_train_normalized, y_train)

    # Predict labels for the test data
    y_pred_sklearn = knn.predict(X_test_normalized)

    # Print the predicted labels
    print("Predicted labels using scikit-learn's KNN:")
    print(y_pred_sklearn)

    # Return the predicted labels if needed
    return y_pred_sklearn

# Example usage:
# y_pred_sklearn = test_knn(X_train_normalized, X_test_normalized, y_train, K)

In [23]:
from sklearn.neighbors import KNeighborsClassifier

# Assuming you have your training data X_train and corresponding labels y_train
# Assuming you have your test data X_test
# Assuming you have your ground truth labels for test data y_test

# Initialize kNN classifier
  # You can set the number of neighbors as per your choice

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_normalized, y_train)
# Fit the classifier to the training data

knn
# Predict the labels for the test data
y_pred_sklearn = knn.predict(X_test_normalized)
y_pred_sklearn
# Calculate accuracy
# accuracy = accuracy_score(y_test, y_pred_sklearn)
# print("Accuracy:", accuracy)

array([1, 2, 1, 2, 2, 0, 2, 2, 2, 2, 0, 1, 0, 1, 1, 1, 1, 2, 2, 0, 0, 1,
       0, 2, 0, 1, 1, 2, 0, 2])

In [24]:
same=0
for i in range(len(y_pred_sklearn)):
  if y_pred_sklearn[i]==y_pred_scratch[i]:
    same+=1
print("accuracy is:",(same/len(y_pred_sklearn))*100)

accuracy is: 100.0
